name: Trigger auto deployment for container-app-jujwtd2gnnqj4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-jujwtd2gnnqj4-AutoDeployTrigger-3411b1d0-ded9-4822-9a56-9c653865219e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJUJWTD2GNNQJ4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJUJWTD2GNNQJ4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJUJWTD2GNNQJ4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPJUJWTD2GNNQJ4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJUJWTD2GNNQJ4_REGISTRY_PASSWORD }}
          containerAppName: container-app-jujwtd2gnnqj4
          resourceGroup: ragchatapp9278
          imageToBuild: default/container-app-jujwtd2gnnqj4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


